<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Ошибка входа</title>
    <link rel="stylesheet" href="./candidates.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body class="flex align-center vh-100">
<div class="container align-center">
    <div class="card shadow p-4 text-center">
        <h2 class="text-primary">Ошибка входа</h2>
        <h4 class="alert-heading">Неверный логин или пароль!</h4>
        <div class="flex justify-content-center gap-4">
            <a href="/login" class="back">Попробовать снова</a>
            <a href="/register" class="back">Регистрация</a>
        </div>
    </div>
</div>
</body>
</html>
